#apiVersion: v1
#kind: Service
#metadata:
#  name: authsvc-service
#spec:
#  selector:
#    app: authsvc
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 9990
#  type: LoadBalancer # You can use NodePort or ClusterIP depending on your environment
